image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test
  - Static Analysis
  - deploy

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
build-start:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pip install -r requirements.txt
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

test-django-backend:
  stage: test
  script:
    - cd django_api
    - python manage.py migrate
    - python manage.py test
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

test-flask-ui:
  stage: test
  script:
    - pytest api_comms/flask_app/test_flask_app.py
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

#flake8:
#  stage: Static Analysis
#  script:
#    - flake8 --ignore=W293,W391 --exclude 'venv/*' --max-line-length=120 .
#  retry:
#    max: 2
#    when:
#      - runner_system_failure
#      - stuck_or_timeout_failure

coverage:
  stage: Static Analysis
  script:
    #ToDo add all of the other tests once the file structures are final
    #- coverage run --omit 'venv/*','*/migrations/*' --source=django_api/company_schema/,django_api/report_schema django_api/manage.py test
    - coverage run --omit venv/*,*test* -m pytest api_comms/flask_app/test_flask_app.py
    - coverage report
    - coverage erase
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

deploy-prod:
  stage: deploy
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs
    - make html
    - cd ..
    - cp -R docs/build/html/_static api_comms/flask_app/_static
    - rm -d -r docs/build/html/_static
    - rm -d -r docs/build/html/_sources
    - mkdir -p api_comms/flask_app/templates/docs
    - mkdir -p api_comms/flask_app/templates/docs/html
    - cp -R docs/build/html api_comms/flask_app/templates/docs/html
    - rm -d -r docs/build
